### ISSUE TITLE
https://github.com:Carrooi/Node-RecursiveMerge.git

### ISSUE THREAD

**Issue by metrue** [metrue/npm-stats#1]
https://github.com:Carrooi/Node-RecursiveMerge.git  cannot get stars  TypeError: Cannot read property 'attribs' of undefined
    at Request._callback (/Users/mhuang/Codes/xstars/lib/utils.js:165:34)
    at Request.self.callback (/Users/mhuang/Codes/xstars/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/mhuang/Codes/xstars/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/mhuang/Codes/xstars/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by metrue** [comment]
fixed
